INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Juan', 'Gómez', 'juan.gomez@example.com', '2023-07-15', 3);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('María', 'Martínez', 'maria.martinez@example.com', '2023-07-12', 2);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Pedro', 'López', 'pedro.lopez@example.com', '2023-07-10', 5);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Ana', 'Fernández', 'ana.fernandez@example.com', '2023-07-20', 1);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Luis', 'García', 'luis.garcia@example.com', '2023-07-18', 4);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Laura', 'Rodríguez', 'laura.rodriguez@example.com', '2023-07-22', 2);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Carlos', 'González', 'carlos.gonzalez@example.com', '2023-07-25', 3);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Sofía', 'Ramírez', 'sofia.ramirez@example.com', '2023-07-14', 1);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Miguel', 'Gómez', 'miguel.gomez@example.com', '2023-07-11', 2);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Elena', 'Martínez', 'elena.martinez@example.com', '2023-07-23', 5);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Andrés', 'López', 'andres.lopez@example.com', '2023-07-19', 1);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Beatriz', 'Fernández', 'beatriz.fernandez@example.com', '2023-07-08', 3);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Javier', 'García', 'javier.garcia@example.com', '2023-07-16', 2);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Isabel', 'Rodríguez', 'isabel.rodriguez@example.com', '2023-07-21', 1);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Pablo', 'González', 'pablo.gonzalez@example.com', '2023-07-26', 4);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Carmen', 'Ramírez', 'carmen.ramirez@example.com', '2023-07-17', 3);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Fernando', 'Gómez', 'fernando.gomez@example.com', '2023-07-13', 2);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Lorena', 'Martínez', 'lorena.martinez@example.com', '2023-07-09', 1);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Juan', 'Gómez', 'juan.gomez@example.com', '2023-07-15', 3);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('María', 'Martínez', 'maria.martinez@example.com', '2023-07-12', 2);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Pedro', 'López', 'pedro.lopez@example.com', '2023-07-10', 5);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Ana', 'Fernández', 'ana.fernandez@example.com', '2023-07-20', 1);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Luis', 'García', 'luis.garcia@example.com', '2023-07-18', 4);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Laura', 'Rodríguez', 'laura.rodriguez@example.com', '2023-07-22', 2);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Carlos', 'González', 'carlos.gonzalez@example.com', '2023-07-25', 3);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Sofía', 'Ramírez', 'sofia.ramirez@example.com', '2023-07-14', 1);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Miguel', 'Gómez', 'miguel.gomez@example.com', '2023-07-11', 2);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Elena', 'Martínez', 'elena.martinez@example.com', '2023-07-23', 5);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Andrés', 'López', 'andres.lopez@example.com', '2023-07-19', 1);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Beatriz', 'Fernández', 'beatriz.fernandez@example.com', '2023-07-08', 3);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Javier', 'García', 'javier.garcia@example.com', '2023-07-16', 2);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Isabel', 'Rodríguez', 'isabel.rodriguez@example.com', '2023-07-21', 1);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Pablo', 'González', 'pablo.gonzalez@example.com', '2023-07-26', 4);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Carmen', 'Ramírez', 'carmen.ramirez@example.com', '2023-07-17', 3);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Fernando', 'Gómez', 'fernando.gomez@example.com', '2023-07-13', 2);
INSERT INTO usuarios (nombre, apellido, email, fecha_libro_prestado, cantidad_ejemplares_prestados) VALUES ('Lorena', 'Martínez', 'lorena.martinez@example.com', '2023-07-09', 1);
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El Prisionero de Azkaban', 10, 'Editorial Salamandra', 'J.K. Rowling');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Cien años de soledad', 5, 'Editorial Sudamericana', 'Gabriel García Márquez');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('1984', 8, 'Editorial Secker and Warburg', 'George Orwell');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El Alquimista', 15, 'Editorial HarperOne', 'Paulo Coelho');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Los juegos del hambre', 12, 'Editorial Scholastic', 'Suzanne Collins');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Harry Potter y la Piedra Filosofal', 20, 'Editorial Bloomsbury', 'J.K. Rowling');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Orgullo y prejuicio', 7, 'Editorial T. Egerton, Whitehall', 'Jane Austen');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El Principito', 18, 'Editorial Reynal & Hitchcock', 'Antoine de Saint-Exupéry');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El Gran Gatsby', 9, 'Editorial Charles Scribner\'s Sons', 'F. Scott Fitzgerald');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Don Quijote de la Mancha', 25, 'Editorial Francisco de Robles', 'Miguel de Cervantes');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Crónica de una muerte anunciada', 6, 'Editorial La Oveja Negra', 'Gabriel García Márquez');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Drácula', 11, 'Editorial Constable & Co.', 'Bram Stoker');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Matar un ruiseñor', 14, 'Editorial J. B. Lippincott & Co.', 'Harper Lee');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El Hobbit', 13, 'Editorial George Allen & Unwin', 'J.R.R. Tolkien');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El señor de los anillos', 30, 'Editorial George Allen & Unwin', 'J.R.R. Tolkien');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Los pilares de la Tierra', 22, 'Editorial Macmillan', 'Ken Follett');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El código Da Vinci', 19, 'Editorial Doubleday', 'Dan Brown');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El retrato de Dorian Gray', 16, 'Editorial Ward, Lock & Co.', 'Oscar Wilde');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Crimen y castigo', 23, 'Editorial The Russian Messenger', 'Fiódor Dostoyevski');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Anna Karenina', 21, 'Editorial The Russian Messenger', 'Lev Tolstói');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El amor en los tiempos del cólera', 17, 'Editorial Oveja Negra', 'Gabriel García Márquez');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Los hermanos Karamazov', 24, 'Editorial The Russian Messenger', 'Fiódor Dostoyevski');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El guardián entre el centeno', 20, 'Editorial Little, Brown and Company', 'J.D. Salinger');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Cien días de soledad', 8, 'Editorial Sudamericana', 'Gabriel García Márquez');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Memorias de una geisha', 14, 'Editorial Alfred A. Knopf', 'Arthur Golden');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('La sombra del viento', 11, 'Editorial Planeta', 'Carlos Ruiz Zafón');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El nombre del viento', 13, 'Editorial Gollancz', 'Patrick Rothfuss');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('1984', 9, 'Editorial Secker and Warburg', 'George Orwell');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Sapiens: De animales a dioses', 16, 'Editorial Vintage', 'Yuval Noah Harari');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Un mundo feliz', 12, 'Editorial Chatto & Windus', 'Aldous Huxley');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Los hombres que no amaban a las mujeres', 18, 'Editorial Norstedts Förlag', 'Stieg Larsson');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El código Da Vinci', 7, 'Editorial Doubleday', 'Dan Brown');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El juego de Ender', 10, 'Editorial Tor Books', 'Orson Scott Card');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('Harry Potter y el cáliz de fuego', 21, 'Editorial Bloomsbury', 'J.K. Rowling');
INSERT INTO libros (titulo, cantidad_ejemplares, editorial, autor) VALUES ('El hobbit', 25, 'Editorial George Allen & Unwin', 'J.R.R. Tolkien');
